def image(index):
    if index == 1:
        print("          ")
        print("          ")
        print("          ")
        print("          ")
        print("          ")
        print("          ")
        print(" _______  ")
    elif index == 2:
        print("          ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|_______  ")
    elif index == 3:
        print("________  ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|_______  ")
    elif index == 4:
        print("________  ")
        print("|      |  ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|_______  ")
    elif index == 5:
        print("________  ")
        print("|      |  ")
        print("|      O  ")
        print("|         ")
        print("|         ")
        print("|         ")
        print("|_______  ")
    elif index == 6:
        print("________  ")
        print("|      |  ")
        print("|      O  ")
        print("|      |  ")
        print("|         ")
        print("|         ")
        print("|_______  ")
    elif index == 7:
        print("________  ")
        print("|      |  ")
        print("|      O  ")
        print("|     /|  ")
        print("|         ")
        print("|         ")
        print("|_______  ")
    elif index == 8:
        print("________  ")
        print("|      |  ")
        print("|      O  ")
        print("|     /|\\")
        print("|         ")
        print("|         ")
        print("|_______  ")
    elif index == 9:
        print("________  ")
        print("|      |  ")
        print("|      O  ")
        print("|     /|\\")
        print("|     /   ")
        print("|         ")
        print("|_______  ")
    elif index == 10:
        print("________  ")
        print("|      |  ")
        print("|      O  ")
        print("|     /|\\")
        print("|     / \\")
        print("|         ")
        print("|_______  ")
